name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build and publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/HealthAPI
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: hospital-system-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{env.DOTNET_ROOT}}/HealthAPI
